name: Build, push, and deploy

on: [ push ]

env:
  docker_image: ghcr.io/navikt/tiltakspenger-mottak:${{ github.sha }}
  PRINT_PAYLOAD: true

jobs:
  build:
    name: Test, build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.2.0
        env:
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
        with:
          arguments: build --continue --no-daemon --no-build-cache

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker build --tag ${docker_image} .
          docker push ${docker_image}

      - name: Notify Slack in case of build failure
        if: ${{ failure() && (github.ref == 'refs/heads/main') }}
        run: |
          curl -X POST --data-urlencode "payload={ \"attachments\": [{ \"pretext\": \"[tiltakspenger-mottak] Build failed :cry:\", \"color\": \"danger\", \"fields\": [ { \"title\": \"Author\", \"value\": \"$AUTHOR\", \"short\": false }, { \"title\": \"Commit\", \"value\": \"<https://github.com/navikt/tiltakspenger-mottak/commit/$GITHUB_SHA|$GITHUB_SHA>\", \"short\": false } ] }] }" $WEBHOOK_URL
        env:
          BRANCH: ${{github.ref }}
          AUTHOR: ${{ github.event.pusher.name }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  deploy-dev:
    name: Deploy to NAIS dev
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yml
          VAR: image=${{ env.docker_image }}
